Manager/Manager/Models/GroupMenu.cs
namespace Manager.Models
{
    public class GroupMenu
    {
        public Guid GroupMenuId { get; set; }
        public string? Title { get; set; }    
        public string? Link { get; set; }    
        public int SortOrder { get; set; }    
    }
}

Manager/Manager/Controllers/GroupMenuController.cs
using Manager.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Manager.Controllers
{
    public class GroupMenuController : BaseController
    {
        private List<Menu> menuList = new List<Menu>();
        public GroupMenuController(MyDbContext dbContext) : base(dbContext)
        {
        }

        public IActionResult Index()
        {
            var result = _dbContext.Menus.Where(x=>x.ParentId==Guid.Empty).ToList();
            ViewBag.Menus = result;
            return View();
        }
        [HttpPost]
        public JsonResult Create(Menu menu)
        {
            menu.MenuId = Guid.NewGuid();
            menu.Title = menu.Title;
            menu.Link = menu.Link;
            menu.ParentId = menu.ParentId;
            _dbContext.Menus.Add(menu);
            _dbContext.SaveChanges();
            return Json(menu);
        }
        [HttpPost]
        public JsonResult Edit(Menu menu)
        {
            var entity = _dbContext.Menus.Where(x=>x.MenuId==menu.MenuId).First();
            entity.Title = menu.Title;
            entity.Link = menu.Link;
            entity.ParentId = menu.ParentId;
            _dbContext.Menus.Update(entity);
            _dbContext.SaveChanges();
            return Json(entity);
        }
        [HttpPost]
        public JsonResult Delete(Guid id)
        {
            var menu = _dbContext.Menus.ToList();
            var entity = menu.Where(x => x.MenuId == id).First();
            var childrentMenu = getChidrentMenu(menu,id);
            _dbContext.Menus.Remove(entity);
            _dbContext.Menus.RemoveRange(childrentMenu);
           
            return Json(entity);
        }
        public List<Menu> getChidrentMenu(List<Menu> menus,Guid id)
        {          
            if (menus.Count > 0)
            {
                var entity = menus.Where(x => x.MenuId == id || x.ParentId == id).ToList();
                var count = entity.Count();
                //if (entity==null)
                //{
                //    return menuList;
                //}
                //else
                //{
                //    menuList.Add(entity);
                //    menus.Remove(entity);
                //}
                //getChidrentMenu(menus, entity.MenuId);
            }
            return menuList;
        }
        public JsonResult GetParentNode()
        {
            var menus = _dbContext.Menus.Select(x => new TreeNodeMenu()
            {
                MenuId = x.MenuId,
                Title = x.Title,
                Link = x.Link,
                ParentId = x.ParentId
            }).ToList();
            List<TreeNodeMenu> result = new List<TreeNodeMenu>();
            result = menus.Where(c=>c.ParentId == Guid.Empty)
                          .Select(c => new TreeNodeMenu() { MenuId = c.MenuId, Title = c.Title, ParentId = c.ParentId, Link = c.Link, data = GetChildren(menus, c.MenuId) })
                          .ToList();
            return Json(result.ToArray());
        }

        public static List<TreeNodeMenu> GetChildren(List<TreeNodeMenu> menus, Guid parentId)
        {
            return menus
                    .Where(c => c.ParentId == parentId)
                    .Select(c => new TreeNodeMenu { MenuId = c.MenuId, Title = c.Title, Link = c.Link, ParentId = c.ParentId, data = GetChildren(menus, c.MenuId) })
                    .ToList();
        }
        [HttpGet]
        public JsonResult GetAllMenu()
        {
            var result = _dbContext.Menus.Select(x => new Menu()
            {
                MenuId = x.MenuId,
                Title = x.Title,
                ParentId = x.ParentId,
                Link = x.Link,
            }).ToList();
            return Json(result);
        }
    }
}

Manager/Manager/Controllers/MenuController.cs
using Manager.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Manager.Controllers
{
    public class MenuController : BaseController
    {
        private List<Menu> menuList = new List<Menu>();
        public MenuController(MyDbContext dbContext) : base(dbContext)
        {
        }

        public IActionResult Index()
        {
            var result = _dbContext.Menus.Where(x=>x.ParentId==Guid.Empty)
                .Select(x=> new Menu
                {
                    MenuId = x.MenuId,
                    Link = x.Link,
                    Title = x.Title,
                    ParentId = x.ParentId,
                }).ToList();
            var language = _dbContext.Languages.ToList();
            ViewBag.Menus = result;
            ViewBag.Language = language;
            return View();
        }
        public JsonResult Get(Guid id)
        {
            var menu = _dbContext.Menus.Find(id);
            return Json(menu);
        }
        [HttpPost]
        public JsonResult Create(Menu menu)
        {
            menu.MenuId = Guid.NewGuid();
            menu.Title = menu.Title;
            menu.Link = menu.Link;
            menu.ParentId = menu.ParentId;
            menu.LanguageId = menu.LanguageId;
            _dbContext.Menus.Add(menu);
            _dbContext.SaveChanges();
            return Json(menu);
        }
        [HttpPost]
        public JsonResult Edit(Menu menu)
        {
            var entity = _dbContext.Menus.Where(x=>x.MenuId==menu.MenuId).First();
            entity.Title = menu.Title;
            entity.Link = menu.Link;
            entity.ParentId = menu.ParentId;
            _dbContext.Menus.Update(entity);
            _dbContext.SaveChanges();
            return Json(entity);
        }
        [HttpPost]
        public JsonResult Delete(Guid id)
        {
            var menu = _dbContext.Menus.ToList();
            var entity = menu.Where(x => x.MenuId == id).First();
          
            _dbContext.Menus.Remove(entity);
            //_dbContext.Menus.RemoveRange(childrentMenu);
           _dbContext.SaveChanges();
            return Json(entity);
        }
       
        public JsonResult GetParentNode()
        {
            var menus = _dbContext.Menus.Select(x => new TreeNodeMenu()
            {
                MenuId = x.MenuId,
                Title = x.Title,
                Link = x.Link,
                ParentId = x.ParentId
            }).ToList();
            List<TreeNodeMenu> result = new List<TreeNodeMenu>();
            result = menus.Where(c=>c.ParentId == Guid.Empty)
                          .Select(c => new TreeNodeMenu() { MenuId = c.MenuId, Title = c.Title, ParentId = c.ParentId, Link = c.Link, data = GetChildren(menus, c.MenuId) })
                          .ToList();
            return Json(result.ToArray());
        }

        public static List<TreeNodeMenu> GetChildren(List<TreeNodeMenu> menus, Guid parentId)
        {
            return menus
                    .Where(c => c.ParentId == parentId)
                    .Select(c => new TreeNodeMenu { MenuId = c.MenuId, Title = c.Title, Link = c.Link, ParentId = c.ParentId, data = GetChildren(menus, c.MenuId) })
                    .ToList();
        }
        [HttpGet]
        public JsonResult GetAllMenu()
        {
            var result = _dbContext.Menus.Select(x => new Menu()
            {
                MenuId = x.MenuId,
                Title = x.Title,
                ParentId = x.ParentId,
                Link = x.Link,
            }).ToList();
            return Json(result);
        }
    }
}

Manager/Manager/Views/GroupMenu/Index.cshtml
@model Manager.Models.GroupMenu;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 



 <main class="page-content">
    <div class="page-header">
      <p class="fw">Danh sách tên miền đen</p>
       <!-- Button HTML (to Trigger Modal) -->
    <button type="button" href="#myModal" role="button" class="btn btn-primary" data-bs-toggle="modal">Thêm mới</button>
     <!-- Modal HTML -->
    <div id="myModal" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Thêm Mới Menu</h5>
                    <button type="button" onclick="HideForm()" class="btn-close btn btn-default" data-bs-dismiss="modal"> <i class="fa fa-times" aria-hidden="true"></i></button>
                </div>
                <div class="modal-body">
                  <form id="myFrom">                                        
                     <div class="mb-3">
                      <input  type="text" class="form-control" hidden id="MenuId" aria-describedby="emailHelp">
                    </div>                  
                      <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label">Tên</label>
                      <input asp-for="Title"  required name="Title" type="text" class="form-control"  id="GroupMenuTitle" aria-describedby="emailHelp">
                    
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label">Link</label>
                      <input asp-for="Link" required name="Link" type="text" class="form-control"  id="GroupMenuLink" aria-describedby="emailHelp">
                    
                    </div>
                     <div class="form-group">
                        <label for="exampleFormControlSelect1">Chọn Parent</label>
                         <div class="dropdown dropdown-tree bt-s" id="firstDropDownTree2" parentId=""></div>
                    </div>
                      <div class="mb-3 text-right">
                      <button type="button" onclick="AddOrUpdate()" class="btn btn-primary btn-add">Thêm</button>
                    </div>
                 </form>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="page-search">
      <div id="accordion">
        <div class="card">
          <div class="card-header" id="headingOne">
            <span><i b-eginzb9zup="" class="fa fa-search" aria-hidden="true"></i></span>
            <h5 class="mb-0">
              <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <i class="fa fa-arrow-down" aria-hidden="true"></i>
              </button>
            </h5>
          </div>
      
          <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
              <div class="input-groups">
                 <form method="get" style="display:flex">
                      <label style="margin-right:10px" for="">Tên Quyền</label>
                    <div>
                    <div>
                    <input type="text" name="filter">
                    </div> 
                    <button type="submit" class="btn btn-primary">Tìm kiếm</button>
                    </div>     
                 </form>    
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="page-content-table">
      <table class="table table-bordered" id="dataTable" cellpadding=0>
        <thead>
          <tr>
           
            <th scope="col">Menu</th>
          </tr>
        </thead>
        <tbody id="tableContext">
             @foreach (var menu in ViewBag.Menus)
             {            
                <tr>    
                     
                     <td class="tableParent"> 
                         <div>
                             <span class="collapses collapsible" data-loaded="false" pid="@menu.MenuId">&nbsp;</span>
                              <span class="tbpermisionname">@menu.Title</span>
                         </div>
                         <div>
                             <button style="margin-right:20px" href="#myModal" data-bs-toggle="modal" onclick="ShowFormUpdate('@menu.MenuId')" type="button" class="btn btn-default">Chỉnh sửa</button>
                           <a style="cursor:pointer" onclick="Delete('@menu.MenuId')" class="btn btn-light">Xóa</a>
                         </div>
                       </td>
                    
                </tr>   
             }
             
            
        </tbody>
      </table>
    </div>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css"/>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
  </main>
    <div class="alert alert-primary" id="notify" role="alert">
       Thêm Mới Thành Công
    </div>


     


    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
      integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
      crossorigin="anonymous"></script>
    <script src="/vendor/dropdowntree/dropdowntree.js"></script>

       
 <script src="~/js/MenuTree.js">
     
</script>
@section Scripts{
   <script src="/js/MyTreeViewMenuTable.js"></script>
}


<script>
    var MenuId = "";
     function Validate(){
        $("input[required]").each(function () {
          let value = $(this).val();
          if (!value) {
            $(this).addClass("s-input-error");
            $(this).attr("validate", false);
            $(this).attr("title", "Không thể bỏ trống");
          } else {
            $(this).removeClass("s-input-error");
            $(this).attr("validate", true);
          }
          });
     }  
    
    function Delete(MenuId) {
        var result = confirm("Bạn có muốn xóa quyền này không?");
        if (result) {
            var Url = "";
            Url = "/Menu/Delete"
            $.ajax({
                type: 'Post',
                url: Url,
                data: { id: MenuId },
                async: false,
                success: function () {
                    window.location.pathname = "/Permission/Index"
                },
                error: function (data) {
                    console.log(data);
                }
            })
        } else {
    
        }
    }
    function HideForm() {
        $('#myFrom')[0].reset();
        $('#ParentId').prop('selectedIndex',0)
        $('.btn-add').html('Thêm');
        var PermissionId = "";
    }
    function ShowFormUpdate(PermissionId) {
        this.PermissionId = PermissionId;
         $('.btn-add').html('Sửa');
        $.ajax({
            type: 'Get',
            url: '/Permission/Get',
            contentType: 'application/json; charset=utf-8',
            data: { id: PermissionId },
            async: false,
            success: function (data) {
               $('#PermissionName').val(data.permissionName);
               this.PermissionId = data.permissionId;
                var option = $('.modal-body option');
                for (var i = 0; i < option.length; i++) {
                    var ParentId = option[i].value;
                    var parent = data.parentId;
                    if (ParentId == data.parentId) {
                        option[i].setAttribute('selected', true);
                    }
                    else {
                        option[i].removeAttribute('selected');
                    }
                }
            }
        })
    }
    function AddOrUpdate(){
        debugger;                                                                                                 
            var data = {
                MenuId:this.MenuId,
                Title:$('#MenuTitle').val(),
                Link:$('#MenuLink').val(),
                ParentId:$('#firstDropDownTree2').attr("parentid")
            };   
            
            this.Validate();
              let validateInput = $('input[validate="false"]');
                if (validateInput && validateInput.length > 0) {
                  alert("Bạn hãy điền đủ các trường thông tin");
                  $(validateInput)[0].focus();
                  return;
                }
            if(this.MenuId==""){
            $.ajax({
                type: 'Post',
                url: '@Url.Action("Create", "Menu")',           
                dataType:"json",
                data: { menu: data },
                async:false,
                success: function (result) {
                    window.location.pathname="/Menu/Index"
                },
                error: function (data) {
                    console.log(data);
                }
            })
            }
            else{           
            $.ajax({
                type: 'Post',
                url: '@Url.Action("Edit", "Permission")',           
                dataType:"json",
                data: { menu: data },
                async:false,
                success: function (result) {
                    window.location.pathname="/Permission/Index"
                },
                error: function (data) {
                    console.log(data);
                }
            })
        }
    }
</script>
<style>
.dropdown-toggle{
    width: 200px;
    display: flex;
    justify-items: center;
    align-items: center;
    justify-content: space-between;
    margin: unset !important;
}
.dropdown-toggle::after{
    display: inline-block;
    width: 0;
    height: 0;
    margin-left: 0.255em;
    vertical-align: 0.255em;
    content: "";
    border-top: 0.4em solid;
    border-right: 0.4em solid transparent;
    /* border-bottom: 1px solid; */
    border-left: 0.4em solid transparent;
}
.dropdown-menu{
    min-width:200px;
}
table tbody tr .tableParent{
    display:flex;
    justify-content:space-between;
    align-items:center;
}
</style>